### ISSUE TITLE
Disable `CURLOPT_SSL_VERIFYPEER`

### ISSUE THREAD

**Issue by 8ctopus** [nimbly/Shuttle#1]
Thank you for a nice http client which I have been using for already quite some time.

I'm currently trying to figure out how to disable `CURLOPT_SSL_VERIFYPEER` and it seems it is not possible as even if the `$curl_options` has it set to false, it will never override the original value (see array + operator https://www.php.net/manual/en/language.operators.array.php)

```php
	protected array $options = [
		CURLOPT_SSL_VERIFYPEER => true,
	];

	public function __construct(
		array $curl_options = [])
	{
		$handle = \curl_init();

		if( $handle === false ){
			throw new HandlerException("Could not initialize cURL.");
		}

		$this->curlHandle = $handle;
		$this->options += $curl_options;
	}
```

I managed to get the expected behavior by modifying the options line like this:

```php
		$this->options = $curl_options + $this->options;
```

**Comment by brentscheffler** [comment]
Resolved in Release 1.0.1
